package constants

const (
	AUTHEN_GATEWAY_HOST                   = "AUTHEN_GATEWAY_HOST"
	AUTHEN_GATEWAY_PATH_SIGNIN            = "AUTHEN_GATEWAY_PATH_SIGNIN"
	AUTHEN_GATEWAY_PATH_GET_TOKENVERSION  = "AUTHEN_GATEWAY_PATH_GET_TOKENVERSION"
	AUTHEN_GATEWAY_PATH_CALL_REVOKE       = "AUTHEN_GATEWAY_PATH_CALL_REVOKE"
	AUTHEN_GATEWAY_PATH_CALL_REFRESHTOKEN = "AUTHEN_GATEWAY_PATH_CALL_REFRESHTOKEN"
)
