package constants

const (
	PATH_STRAPI_SIGNIN              = "PATH_STRAPI_SIGNIN"
	HOST_STRAPI_SERVICE             = "HOST_STRAPI_SERVICE"
	PATH_STRAPI_INFORMATION_GATEWAY = "PATH_STRAPI_INFORMATION_GATEWAY"
	PATH_STRAPI_REFRESHTOKEN        = "PATH_STRAPI_REFRESHTOKEN"
	PATH_STRAPI_FORGET_PASSWORD     = "PATH_STRAPI_FORGET_PASSWORD"
	PATH_STRAPI_RESET_PASSWORD      = "PATH_STRAPI_RESET_PASSWORD"
	PATH_STRAPI_REGISTER            = "PATH_STRAPI_REGISTER"
	PATH_STRAPI_CALLBACK_GOOGLE     = "PATH_STRAPI_CALLBACK_GOOGLE"
	PATH_STRAPI_CALLBACK_FACEBOOK   = "PATH_STRAPI_CALLBACK_FACEBOOK"
)
